language: cpp

dist: trusty
sudo: required



cache:
  directories:
  - '$HOME/.sonar/cache'

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="CC=clang && CXX=clang++"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
      env:
        - MATRIX_EVAL="CC=gcc-5 && CXX=g++-5"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-6
      env:
        - MATRIX_EVAL="CC=gcc-6 && CXX=g++-6"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-7
        sonarcloud:
          organization: "droccom-github"
      env:
        - MATRIX_EVAL="CC=gcc-7 && CXX=g++-7"
    - os: linux
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-trusty-5.0
          packages:
            - g++-7
            - clang-5.0
      env:
        - MATRIX_EVAL="CC=clang-5.0 && CXX=clang++-5.0"

before_install:
        - eval "${MATRIX_EVAL}"
install:
        - git clone --single-branch https://github.com/fastflow/fastflow.git
        - ln -s fastflow/ff ff
script:
        - mkdir build && cd build
        - cmake ..
        - make
        - ctest
        - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$MATRIX_EVAL" == "CC=gcc-7 && CXX=g++-7" ]; then cp ../sonar-project.properties . && build-wrapper-linux-x86-64 --out-dir bw-output make clean all && sonar-scanner ; fi
